#!/bin/sh
### BEGIN INIT INFO
# Provides:    boarded
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Board display mini web server
### END INIT INFO

#PROC=/usr/bin/python
ARGS='/root/Boarded/boarded.py'
PIDFILE=/var/run/boarded.pid

case "$1" in
  start)
    start-stop-daemon --start --pidfile $PIDFILE --background --make-pidfile --startas $ARGS
  ;;
  stop)
    start-stop-daemon --stop --pidfile $PIDFILE --retry TERM/10/KILL/5 && rm $PIDFILE
  ;;
  restart|reload|force-reload)
    $0 stop
    $0 start
  ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 2
  ;;
esac
exit 0


